name: flutter_gqtg
description: 浙江股权交易中心登记托管app

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1
author: 朱艳波 <zyb@zjex.com.cn>
homepage: http://10.88.2.202/zyb/flutter_gqtg

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  uuid: ^2.0.2
  qr_code_scanner: 0.0.12
  package_info: 0.4.0+6
  # device_info: 0.4.0+2
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  fluro: ^1.4.0
  # Toast插件 https://github.com/OpenFlutter/flutter_oktoast
  oktoast: ^2.1.8
  # 网络库 https://github.com/flutterchina/dio
  dio: ^2.1.10
  # https://github.com/ReactiveX/rxdart
  rxdart: ^0.21.0
  # Dart 常用工具类库 https://github.com/Sky24n/common_utils
  common_utils: ^1.1.1
  # Flutter 常用工具类库 https://github.com/Sky24n/flustars
  flustars: ^0.2.5+1
  # Flutter UI组件库 https://github.com/flutterchina/flukit. 
  flukit: ^1.0.0
  # 启动URL的插件 https://github.com/flutter/plugins/tree/master/packages/url_launcher
  url_launcher: 5.0.2
  # 图片选择插件 https://github.com/flutter/plugins/tree/master/packages/image_picker
  image_picker: 0.6.0+8
  # 侧滑删除 https://github.com/letsar/flutter_slidable
  flutter_slidable: ^0.5.3
  # WebView插件 https://github.com/flutter/plugins/tree/master/packages/webview_flutter
  webview_flutter: 0.3.13 
  # flutter_webview_plugin: 0.3.7
  # 处理键盘事件 https://github.com/diegoveloper/flutter_keyboard_actions
  keyboard_actions: ^2.1.1
  # 列表悬浮头 https://github.com/fluttercommunity/flutter_sticky_headers
  sticky_headers: ^0.1.8
  # 城市选择列表 https://github.com/flutterchina/azlistview
  azlistview: ^0.1.2
  # 用于日历功能 https://github.com/apptreesoftware/date_utils
  date_utils: ^0.1.0+2
  # 手势识别 https://github.com/aleksanderwozniak/simple_gesture_detector
  simple_gesture_detector: ^0.1.3
  # 曲线图表 https://github.com/aeyrium/bezier-chart
  # bezier_chart: ^1.0.7
  # https://github.com/Dn-a/flutter_tags
  flutter_tags: 0.3.1
  #A flutter plugin for adapting screen and font size.
  #Let your UI display a reasonable layout on different screen sizes!
  #https://github.com/OpenFlutter/flutter_ScreenUtil
  flutter_screenutil: 0.5.2
  dropdown_formfield: 0.1.0
  # image_picker: 0.6.0+9
  path_drawing: 0.4.1
  gzx_dropdown_menu: 1.0.2
  flutter_picker: ^1.0.13
  event_bus:  1.1.0
  connectivity: 0.4.3+2
  shared_preferences: ^0.5.3+2
  flutter_image_compress: ^0.6.2
  path_provider: ^1.1.2 
  dotted_border: 1.0.2
  provide: ^1.0.2
  flutter_downloader: ^1.1.9
  progress_dialog: ^1.1.0+1
  # permission_handler: ^3.2.2
  # flutter_plugin_pdf_viewer: ^1.0.7
  photo_view: ^0.4.2
  flutter_paginator: ^0.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter



# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/data/
    - assets/images/
    - assets/images/login/
    - assets/images/home/
    - assets/images/store/
    - assets/images/store/2.0x/
    - assets/images/store/3.0x/
    - assets/images/splash/
    - assets/images/splash/2.0x/
    - assets/images/splash/3.0x/
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: iconfont
      fonts:
        - asset: assets/fonts/iconfont.ttf
    - family: elementfont
      fonts:
        - asset: assets/fonts/element-icons.ttf
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
